# примеры API-запросов

@baseUrl = http://localhost:8000/api
@token = 0de3e0925b95e7729c56a04c1f59d9f6f54af8f7

# получение объявлений
GET {{baseUrl}}/advertisements/
Content-Type: application/json

###

# создание объявления
POST {{baseUrl}}/advertisements/
Content-Type: application/json
Authorization: Token {{token}}

{
  "title": "Шкаф IKEA",
  "description": "Срочно"
}

###

# попытка поменять объявление
PATCH {{baseUrl}}/advertisements/1/
Content-Type: application/json
Authorization: Token {{token}}

{
  "status": "CLOSED"
}

###

# фильтрация по создателю
GET {{baseUrl}}/advertisements/?creator=2
Content-Type: application/json

###

# фильтрация по дате
GET {{baseUrl}}/advertisements/?created_at_before=2020-10-01
Content-Type: application/json

###

# просмотр избранного

GET {{baseUrl}}/advertisements/favorites/
Accept: application/json
Authorization: Token {{token}}

###

# добавление в избранное

POST {{baseUrl}}/advertisements/8/favorites/
Accept: application/json
Authorization: Token {{token}}

###

# удаление из избранного

DELETE {{baseUrl}}/advertisements/8/favorites/
Accept: application/json
Authorization: Token {{token}}
