# Generated by Django 4.1.7 on 2023-03-26 04:52

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Phone",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=64)),
                ("price", models.DecimalField(decimal_places=2, max_digits=11)),
                ("image", models.URLField()),
                ("release_date", models.DateField()),
                ("lte_exists", models.BooleanField()),
                ("slug", models.SlugField(max_length=64, unique=True)),
            ],
        ),
    ]
